package com.cx.pojo;

public class Flight {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.flight_id
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    private String flightId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.flight_name
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    private String flightName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.flight_from
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    private String flightFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.flight_arr
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    private String flightArr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.flight_ftime
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    private String flightFtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.flight_atime
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    private String flightAtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.flight_id
     *
     * @return the value of flight.flight_id
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    public String getFlightId() {
        return flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.flight_id
     *
     * @param flightId the value for flight.flight_id
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    public void setFlightId(String flightId) {
        this.flightId = flightId == null ? null : flightId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.flight_name
     *
     * @return the value of flight.flight_name
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    public String getFlightName() {
        return flightName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.flight_name
     *
     * @param flightName the value for flight.flight_name
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    public void setFlightName(String flightName) {
        this.flightName = flightName == null ? null : flightName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.flight_from
     *
     * @return the value of flight.flight_from
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    public String getFlightFrom() {
        return flightFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.flight_from
     *
     * @param flightFrom the value for flight.flight_from
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    public void setFlightFrom(String flightFrom) {
        this.flightFrom = flightFrom == null ? null : flightFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.flight_arr
     *
     * @return the value of flight.flight_arr
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    public String getFlightArr() {
        return flightArr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.flight_arr
     *
     * @param flightArr the value for flight.flight_arr
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    public void setFlightArr(String flightArr) {
        this.flightArr = flightArr == null ? null : flightArr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.flight_ftime
     *
     * @return the value of flight.flight_ftime
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    public String getFlightFtime() {
        return flightFtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.flight_ftime
     *
     * @param flightFtime the value for flight.flight_ftime
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    public void setFlightFtime(String flightFtime) {
        this.flightFtime = flightFtime == null ? null : flightFtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.flight_atime
     *
     * @return the value of flight.flight_atime
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    public String getFlightAtime() {
        return flightAtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.flight_atime
     *
     * @param flightAtime the value for flight.flight_atime
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    public void setFlightAtime(String flightAtime) {
        this.flightAtime = flightAtime == null ? null : flightAtime.trim();
    }

	@Override
	public String toString() {
		return "Flight [flightId=" + flightId + ", flightName=" + flightName + ", flightFrom=" + flightFrom
				+ ", flightArr=" + flightArr + ", flightFtime=" + flightFtime + ", flightAtime=" + flightAtime + "]";
	}
    
}