package com.cx.pojo;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_id
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.price_id
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    private String priceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_id
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_time
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    private String orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.adt_psgnum
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    private Integer adtPsgnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.kid_psgnum
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    private Integer kidPsgnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.amount
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.statement
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    private String statement;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_id
     *
     * @return the value of orders.order_id
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_id
     *
     * @param orderId the value for orders.order_id
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.price_id
     *
     * @return the value of orders.price_id
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    public String getPriceId() {
        return priceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.price_id
     *
     * @param priceId the value for orders.price_id
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    public void setPriceId(String priceId) {
        this.priceId = priceId == null ? null : priceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_id
     *
     * @return the value of orders.user_id
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_id
     *
     * @param userId the value for orders.user_id
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_time
     *
     * @return the value of orders.order_time
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_time
     *
     * @param orderTime the value for orders.order_time
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime == null ? null : orderTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.adt_psgnum
     *
     * @return the value of orders.adt_psgnum
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    public Integer getAdtPsgnum() {
        return adtPsgnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.adt_psgnum
     *
     * @param adtPsgnum the value for orders.adt_psgnum
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    public void setAdtPsgnum(Integer adtPsgnum) {
        this.adtPsgnum = adtPsgnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.kid_psgnum
     *
     * @return the value of orders.kid_psgnum
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    public Integer getKidPsgnum() {
        return kidPsgnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.kid_psgnum
     *
     * @param kidPsgnum the value for orders.kid_psgnum
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    public void setKidPsgnum(Integer kidPsgnum) {
        this.kidPsgnum = kidPsgnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.amount
     *
     * @return the value of orders.amount
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.amount
     *
     * @param amount the value for orders.amount
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.statement
     *
     * @return the value of orders.statement
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    public String getStatement() {
        return statement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.statement
     *
     * @param statement the value for orders.statement
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    public void setStatement(String statement) {
        this.statement = statement == null ? null : statement.trim();
    }

	@Override
	public String toString() {
		return "Order [orderId=" + orderId + ", priceId=" + priceId + ", userId=" + userId + ", orderTime=" + orderTime
				+ ", adtPsgnum=" + adtPsgnum + ", kidPsgnum=" + kidPsgnum + ", amount=" + amount + ", statement="
				+ statement + "]";
	}
    
}