package com.cx.pojo;

public class Passenger {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.passen_id
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    private String passenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.user_id
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.order_id
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.passen_linsen
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    private String passenLinsen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.passen_name
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    private String passenName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.passen_type
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    private String passenType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.passen_ltype
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    private String passenLtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.passen_id
     *
     * @return the value of passenger.passen_id
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    public String getPassenId() {
        return passenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.passen_id
     *
     * @param passenId the value for passenger.passen_id
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    public void setPassenId(String passenId) {
        this.passenId = passenId == null ? null : passenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.user_id
     *
     * @return the value of passenger.user_id
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.user_id
     *
     * @param userId the value for passenger.user_id
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.order_id
     *
     * @return the value of passenger.order_id
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.order_id
     *
     * @param orderId the value for passenger.order_id
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.passen_linsen
     *
     * @return the value of passenger.passen_linsen
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    public String getPassenLinsen() {
        return passenLinsen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.passen_linsen
     *
     * @param passenLinsen the value for passenger.passen_linsen
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    public void setPassenLinsen(String passenLinsen) {
        this.passenLinsen = passenLinsen == null ? null : passenLinsen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.passen_name
     *
     * @return the value of passenger.passen_name
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    public String getPassenName() {
        return passenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.passen_name
     *
     * @param passenName the value for passenger.passen_name
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    public void setPassenName(String passenName) {
        this.passenName = passenName == null ? null : passenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.passen_type
     *
     * @return the value of passenger.passen_type
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    public String getPassenType() {
        return passenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.passen_type
     *
     * @param passenType the value for passenger.passen_type
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    public void setPassenType(String passenType) {
        this.passenType = passenType == null ? null : passenType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.passen_ltype
     *
     * @return the value of passenger.passen_ltype
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    public String getPassenLtype() {
        return passenLtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.passen_ltype
     *
     * @param passenLtype the value for passenger.passen_ltype
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    public void setPassenLtype(String passenLtype) {
        this.passenLtype = passenLtype == null ? null : passenLtype.trim();
    }

	@Override
	public String toString() {
		return "Passenger [passenId=" + passenId + ", userId=" + userId + ", orderId=" + orderId + ", passenLinsen="
				+ passenLinsen + ", passenName=" + passenName + ", passenType=" + passenType + ", passenLtype="
				+ passenLtype + "]";
	}
}