package com.cx.pojo;

public class Price {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.price_id
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    private String priceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.flight_id
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    private String flightId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.seat_type
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    private String seatType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.flight_price
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    private Integer flightPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.flight_seats
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    private Integer flightSeats;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.price_id
     *
     * @return the value of price.price_id
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    public String getPriceId() {
        return priceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.price_id
     *
     * @param priceId the value for price.price_id
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    public void setPriceId(String priceId) {
        this.priceId = priceId == null ? null : priceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.flight_id
     *
     * @return the value of price.flight_id
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    public String getFlightId() {
        return flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.flight_id
     *
     * @param flightId the value for price.flight_id
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    public void setFlightId(String flightId) {
        this.flightId = flightId == null ? null : flightId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.seat_type
     *
     * @return the value of price.seat_type
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    public String getSeatType() {
        return seatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.seat_type
     *
     * @param seatType the value for price.seat_type
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    public void setSeatType(String seatType) {
        this.seatType = seatType == null ? null : seatType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.flight_price
     *
     * @return the value of price.flight_price
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    public Integer getFlightPrice() {
        return flightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.flight_price
     *
     * @param flightPrice the value for price.flight_price
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    public void setFlightPrice(Integer flightPrice) {
        this.flightPrice = flightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.flight_seats
     *
     * @return the value of price.flight_seats
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    public Integer getFlightSeats() {
        return flightSeats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.flight_seats
     *
     * @param flightSeats the value for price.flight_seats
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    public void setFlightSeats(Integer flightSeats) {
        this.flightSeats = flightSeats;
    }

	@Override
	public String toString() {
		return "Price [priceId=" + priceId + ", flightId=" + flightId + ", seatType=" + seatType + ", flightPrice="
				+ flightPrice + ", flightSeats=" + flightSeats + "]";
	}
    
}