package com.cx.dao;

import com.cx.pagelist.PageInfo;
import com.cx.pojo.Admin;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Sun Aug 26 17:07:13 CST 2018
     */
    int deleteByPrimaryKey(String adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Sun Aug 26 17:07:13 CST 2018
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Sun Aug 26 17:07:13 CST 2018
     */
    Admin selectByPrimaryKey(String adminId);
   
    Admin selectByNAP(@Param("admin_name")String Name,@Param("admin_password")String Pwd);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Sun Aug 26 17:07:13 CST 2018
     */
    List<Admin> selectAllListPage(@Param("page") PageInfo page);
    List<Admin> selectByPower(String power);
    List<Admin>selectByname(String adminName);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Sun Aug 26 17:07:13 CST 2018
     */
    int updateByPrimaryKey(Admin record);
}