package com.cx.dao;

import com.cx.pagelist.PageInfo;
import com.cx.pojo.Flight;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface FlightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    int deleteByPrimaryKey(String flightId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    int insert(Flight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    Flight selectByPrimaryKey(String flightId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    List<Flight> selectAllListPage(@Param("page") PageInfo page);
    List<Flight> selectBydetailListPage(@Param("flight_from")String flightFrom,@Param("flight_arr")String flightArr, @Param("flight_ftime")String flightFtime,@Param("page") PageInfo page);
    
    List<Flight> selectBydetail(@Param("flight_from")String flightFrom,@Param("flight_arr")String flightArr, @Param("flight_ftime")String flightFtime);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbg.generated Tue Aug 21 15:10:36 CST 2018
     */
    int updateByPrimaryKey(Flight record);
}