package com.cx.dao;

import com.cx.pojo.Order;
import java.util.List;



public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    Order selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    List<Order> selectAll();
    List<Order> selectByUserid(String userid);
  
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Aug 23 17:29:01 CST 2018
     */
    int updateByPrimaryKey(Order record);
}