package com.cx.dao;

import com.cx.pojo.Passenger;
import java.util.List;

public interface PassengerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    int deleteByPrimaryKey(String passenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    int insert(Passenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    Passenger selectByPrimaryKey(String passenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    List<Passenger> selectAll();
    List<Passenger> selectByUserId(String userid);
    List<Passenger> selectBysearch(String search);
    List<Passenger> selectByOrderId(String orderid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbg.generated Mon Aug 20 19:52:39 CST 2018
     */
    int updateByPrimaryKey(Passenger record);
}