package com.cx.dao;

import com.cx.pojo.Price;
import java.util.List;

public interface PriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    int deleteByPrimaryKey(String priceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    int insert(Price record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    Price selectByPrimaryKey(String priceId);
    Integer selectmixByflId(String flightId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    List<Price> selectAll();
    List<Price> selectByFlid(String flightId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Mon Aug 20 15:15:13 CST 2018
     */
    int updateByPrimaryKey(Price record);
}