package com.cx.dao;

import com.cx.pagelist.PageInfo;
import com.cx.pojo.User;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Fri Aug 17 14:21:14 CST 2018
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Fri Aug 17 14:21:14 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Fri Aug 17 14:21:14 CST 2018
     */
    User selectByPrimaryKey(String userId);
    User selectByEmail(String email);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Fri Aug 17 14:21:14 CST 2018
     */
    List<User> selectAllListPage(@Param("page") PageInfo page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Fri Aug 17 14:21:14 CST 2018
     */
    int updateByPrimaryKey(User record);
}